# Generated by Hype
require 'C:/Users/Mau/Desktop/HyperTensioN_U/Hypertension_U'

module Counter
  include Hypertension_U
  extend self

  #-----------------------------------------------
  # Domain
  #-----------------------------------------------

  @domain = {
    # Operators
    'add_one' => 1.0,
    # Methods
    'count' => [
      'increment',
      'goal_reached'
    ]
  }

  #-----------------------------------------------
  # Axioms
  #-----------------------------------------------

  def empty_axiom(var)
    return true if true
  end

  def at_axiom(current)
    return true if not (not (@state['at'].include?([current])))
  end

  #-----------------------------------------------
  # Operators
  #-----------------------------------------------

  def add_one(current, successor, goal)
    return unless (empty_axiom(current) and at_axiom(current))
    apply(
      # Add effects
      [
        ['at', successor]
      ],
      # Del effects
      [
        ['at', current]
      ]
    )
  end

  #-----------------------------------------------
  # Methods
  #-----------------------------------------------

  def increment(goal)
    current = ''
    successor = ''
    generate(
      # Positive preconditions
      [
        ['at', current],
        ['next', current, successor]
      ],
      # Negative preconditions
      [], current, successor
    ) {
      yield [
        ['add_one', current, successor, goal],
        ['count', goal]
      ]
    }
  end

  def goal_reached(goal)
    if applicable?(
      # Positive preconditions
      [
        ['at', goal]
      ],
      # Negative preconditions
      []
    )
      yield []
    end
  end
end