# Generated by Hype
require_relative 'cookie.ujshop'

# Objects
bob = 'bob'
home = 'home'
cookie_store = 'cookie_store'

Cookie.problem(
  # Start
  {
    'at' => [
      [bob, home]
    ],
    'have' => []
  },
  # Tasks
  [
    ['get_cookie', bob, home, cookie_store]
  ],
  # Debug
  ARGV.first == '-d'
)