# Generated by Hype
require_relative 'search.ujshop'

# Objects
robot = 'robot'
start = 'start'
goal = 'goal'

Search.problem(
  # Start
  {
    'at' => [
      [robot, start]
    ],
    'visited' => [],
    'call' => []
  },
  # Tasks
  [
    ['forward', robot, goal]
  ],
  # Debug
  ARGV.first == 'debug',
  # Maximum plans found
  ARGV[1] ? ARGV[1].to_i : -1,
  # Minimum probability for plans
  ARGV[2] ? ARGV[2].to_f : 0
)